apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagrange-onebot.fullname" . }}
  labels:
    {{- include "lagrange-onebot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "lagrange-onebot.selectorLabels" . | nindent 4 }}
