apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagrange-onebot.fullname" . }}-portal
  labels:
    {{- include "lagrange-onebot.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      {{- include "lagrange-onebot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: portal
  template:
    metadata:
      {{- with .Values.portal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lagrange-onebot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: portal
    spec:
      {{- with .Values.portal.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lagrange-onebot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.portal.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-portal
          securityContext:
            {{- toYaml .Values.portal.securityContext | nindent 12 }}
          image: "nginx:alpine"
          imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.portal.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
            {{- with .Values.portal.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "lagrange-onebot.fullname" . }}-portal-nginx
            defaultMode: 0644
        {{- with .Values.portal.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.portal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.portal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.portal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}